/*
* Copyright (c) 2019-2021, NVIDIA CORPORATION.  All rights reserved.
*
* NVIDIA CORPORATION and its licensors retain all intellectual property
* and proprietary rights in and to this software, related documentation
* and any modifications thereto.  Any use, reproduction, disclosure or
* distribution of this software and related documentation without an express
* license agreement from NVIDIA CORPORATION is strictly prohibited.
*/
//Fully optimized file by RedPixel

#ifndef RTXGI_DDGI_IRRADIANCE_HLSL
#define RTXGI_DDGI_IRRADIANCE_HLSL

#include "ProbeCommon.ush"

struct DDGIVolumeResources
{
    Texture2D<float4> probeIrradianceSRV;
    Texture2D<float4> probeDistanceSRV;
#if RTXGI_DDGI_PROBE_RELOCATION
    Texture2D<float4> probeOffsetsSRV;
#endif
#if RTXGI_DDGI_PROBE_CLASSIFICATION
    Texture2D<uint>   probeStatesSRV;
#endif
    SamplerState      bilinearSampler;
};

float3 DDGIGetSurfaceBias(float3 n, float3 v, DDGIVolumeDescGPU vol)
{
    return mad(n, vol.normalBias, -v * vol.viewBias);
}

float DDGIGetVolumeBlendWeight(float3 wp, DDGIVolumeDescGPU vol)
{
    float4 qConj = RTXGIQuaternionConjugate(vol.rotation);
    float3 p = RTXGIQuaternionRotate(wp - vol.origin, qConj);
    float3 halfExtent = 0.5f * (vol.probeGridSpacing * (vol.probeGridCounts - 1));
    p += halfExtent;
    float3 invSpacing = rcp(vol.probeGridSpacing);
    float3 probeCoords = p * invSpacing;
    float3 over = (float3)(vol.probeGridCounts - 1) - probeCoords;
    float3 a = saturate(probeCoords);
    float3 b = saturate(over);
    return (a.x * a.y * a.z) * (b.x * b.y * b.z);
}

float3 DDGIGetVolumeIrradiance(
    float3 worldPosition,
    float3 surfaceBias,
    float3 direction,
    DDGIVolumeDescGPU volume,
    DDGIVolumeResources resources)
{
    float3 irradiance = 0;
    float  accumulatedWeights = 0;

    const float4 qConj = RTXGIQuaternionConjugate(volume.rotation);
    const float3 biasedWorldPosition = worldPosition + surfaceBias;
    const float3 invSpacing = rcp(volume.probeGridSpacing);
    const float3 exponent = volume.probeIrradianceEncodingGamma * 0.5f;

    int3 baseProbeCoords = DDGIGetBaseProbeGridCoords(biasedWorldPosition, volume.origin, volume.rotation, volume.probeGridCounts, volume.probeGridSpacing);
    float3 baseProbeWorldPosition = DDGIGetProbeWorldPosition(baseProbeCoords, volume.origin, volume.rotation, volume.probeGridCounts, volume.probeGridSpacing);

    float3 distanceVolumeSpace = RTXGIQuaternionRotate(biasedWorldPosition - baseProbeWorldPosition, qConj);
    float3 alpha = saturate(distanceVolumeSpace * invSpacing);

    [unroll]
    for (int i = 0; i < 8; ++i)
    {
        const int ox =  (i     ) & 1;
        const int oy = ((i >> 1) & 1);
        const int oz = ((i >> 2) & 1);

        int3 adjCoords = clamp(baseProbeCoords + int3(ox,oy,oz), int3(0,0,0), volume.probeGridCounts - int3(1,1,1));

    #if RTXGI_DDGI_PROBE_RELOCATION
        #if RTXGI_DDGI_INFINITE_SCROLLING_VOLUME
            float3 adjWS = DDGIGetProbeWorldPositionWithOffset(adjCoords, volume.origin, volume.rotation, volume.probeGridCounts, volume.probeGridSpacing, volume.probeScrollOffsets, resources.probeOffsetsSRV);
        #else
            float3 adjWS = DDGIGetProbeWorldPositionWithOffset(adjCoords, volume.origin, volume.rotation, volume.probeGridCounts, volume.probeGridSpacing, resources.probeOffsetsSRV);
        #endif
    #else
        float3 adjWS = DDGIGetProbeWorldPosition(adjCoords, volume.origin, volume.rotation, volume.probeGridCounts, volume.probeGridSpacing);
    #endif

        const int adjIndex = DDGIGetProbeIndex(adjCoords, volume.probeGridCounts);

    #if RTXGI_DDGI_PROBE_CLASSIFICATION
        {
        #if RTXGI_DDGI_INFINITE_SCROLLING_VOLUME
            const int sIndex = DDGIGetProbeIndexOffset(adjIndex, volume.probeGridCounts, volume.probeScrollOffsets);
        #else
            const int sIndex = adjIndex;
        #endif
            const int2 tp = DDGIGetProbeTexelPosition(sIndex, volume.probeGridCounts);
            if (resources.probeStatesSRV[tp] == PROBE_STATE_INACTIVE) continue;
        }
    #endif

        float3 v0 = adjWS - worldPosition;
        float3 v1 = adjWS - biasedWorldPosition;

        const float3 worldPosToAdjProbe   = normalize(v0);
        const float  biasedDist           = length(v1);
        const float3 biasedPosToAdjProbe  = v1 * rcp(max(biasedDist, 1e-20f));

        float3 trix = (2.0f * alpha - 1.0f);
        float3 tri  = (1.0f - alpha) + float3((float)ox, (float)oy, (float)oz) * trix;
        tri = max(tri, 0.001f);
        float  triW = tri.x * tri.y * tri.z;

        float wrap = mad(dot(worldPosToAdjProbe, direction), 0.5f, 0.5f);
        float w = wrap * wrap + 0.2f;
        float weight = w;

        float2 oct = DDGIGetOctahedralCoordinates(-biasedPosToAdjProbe);
    #if RTXGI_DDGI_INFINITE_SCROLLING_VOLUME
        float2 probeUV = DDGIGetProbeUV(adjIndex, oct, volume.probeGridCounts, volume.probeNumDistanceTexels, volume.probeScrollOffsets);
    #else
        float2 probeUV = DDGIGetProbeUV(adjIndex, oct, volume.probeGridCounts, volume.probeNumDistanceTexels);
    #endif
        float2 fd = resources.probeDistanceSRV.SampleLevel(resources.bilinearSampler, probeUV, 0).rg;

        const float mean = fd.x;
        const float var  = abs(mad(fd.x, fd.x, -fd.y));
        const float v    = max(biasedDist - mean, 0.0f);
        const float cheb = var * rcp(var + v * v);
        const float cheb3 = cheb * cheb * cheb;
        weight *= max(0.05f, cheb3);
        weight  = max(0.000001f, weight);

        const float c = 0.2f;
        const float m = step(c, weight);
        const float invc2 = 1.0f / (c * c);
        const float weightCrushed = (weight * weight * weight) * invc2;
        weight = mad(m, (weight - weightCrushed), weightCrushed); // (m?weight:weightCrushed)

        weight *= triW;

        oct = DDGIGetOctahedralCoordinates(direction);
    #if RTXGI_DDGI_INFINITE_SCROLLING_VOLUME
        probeUV = DDGIGetProbeUV(adjIndex, oct, volume.probeGridCounts, volume.probeNumIrradianceTexels, volume.probeScrollOffsets);
    #else
        probeUV = DDGIGetProbeUV(adjIndex, oct, volume.probeGridCounts, volume.probeNumIrradianceTexels);
    #endif
        float3 probeIrr = resources.probeIrradianceSRV.SampleLevel(resources.bilinearSampler, probeUV, 0).rgb;
        probeIrr = pow(probeIrr, exponent);

        irradiance += probeIrr * weight;
        accumulatedWeights += weight;
    }

    if (accumulatedWeights == 0.0f) return 0.0f.xxx;

    irradiance *= rcp(accumulatedWeights);
    irradiance *= irradiance;
    irradiance *= RTXGI_2PI;
#if (RTXGI_DDGI_FORMAT_IRRADIANCE == 0)
    irradiance *= 1.0989f;
#endif
    return irradiance;
}

#endif // RTXGI_DDGI_IRRADIANCE_HLSL